test:
  name: fiscobcos-caliper-contract
  description: This is a solidity Contract of FISCO BCOS for caliper
  clients:
    - type: local
      number: 1
  rounds:
  - label: PerChaseCompany
    description: fiscobcos-caliper-test
    txNumber:
    - 10
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    callback: ./PerChaseCompany.js
  - label: TransCompany
    description: fiscobcos-caliper-test
    txNumber:
    - 10
    rateControl:
    - type: fixed-rate
      opts:
        tps: 10
    callback: ./TransCompany.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - node0
    - node1
    - node2
    - node3
  process:
    - command: node
      arguments: fiscoBcosClientWorker.js
      multiOutput: avg
  interval: 0.5
