server:
  port: 8080
  session:
    timeout: 60
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistics?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
banner:
  charset: UTF-8
system:
  hexPrivateKey: "1753f860fb224bc54ba38b6544d9d97d75062ec25083863368fab8a916714d85"
  groupId: 1
  contract:
    logisticsControllerAddress: "0x92d8f3a282c1045295fe121a8f6d96e621501523"
cryptoMaterial:
  certPath: conf
network:
  peers:
    - 127.0.0.1:20200
    - 127.0.0.1:20201

